### ISSUE TITLE
Inompatibility with Gazebo versions less 9.0.0

### ISSUE THREAD

**Issue by Delbb** [nlamprian/gazebo_model_destroyer_plugin#1]
For Gazebo versions less than 9.0.0 the code doesn't compile since the method `ModelByName` is new in this version (located in gazebo_model_destroyer_plugin.cpp line 76). With an older version, using the method `GetModel` instead fix the compilation error and the plugin works fine.

**Comment by nlamprian** [comment]
Thanks for the feedback. I'll address this promptly.
