### ISSUE TITLE
header file not found 'Destroy.h'

### ISSUE THREAD

**Issue by addy1997** [nlamprian/gazebo_model_destroyer_plugin#2]
Hello there, 

While trying to use this plugin, I ran into this error.

file not found 'Destroy.h'

https://github.com/nlamprian/gazebo_model_destroyer_plugin/blob/e97a2eb882073d9dfb3b76355918d7a676daf8a2/include/gazebo_model_destroyer_plugin/gazebo_model_destroyer_plugin.h#L13

Please can you suggest something?
Thanks

**Comment by nlamprian** [comment]
This is a service header file. The error means the file has not been generated. Make sure to use one of the ROS build tools, eg catkin. If you did that, then I'd need more information.

**Comment by addy1997** [comment]
> This is a service header file. The error means the file has not been generated. Make sure to use one of the ROS build tools, eg catkin. If you did that, then I'd need more information.

It was a path-related issue. Fixed it. Thanks
